package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

var DefaultModIDs = []string{"5590619"}

// EnsureConfigTree seeds a config directory with safe defaults.
// Uses a random RCON password and default port 27015.
func EnsureConfigTree(root string) error {
	return EnsureConfigTreeForProfile(root, "", 27015)
}

// EnsureConfigTreeForProfile seeds a config directory with profile-specific RCON settings.
// If rconPassword is empty, a random password is generated.
func EnsureConfigTreeForProfile(root string, rconPassword string, rconPort int) error {
	if err := os.MkdirAll(root, 0o755); err != nil {
		return err
	}
	if rconPassword == "" {
		rconPassword = GenerateRandomPassword()
	}
	if rconPort <= 0 {
		rconPort = 27015
	}
	defaults := map[string]string{
		"Game.ini":             defaultGameINI(rconPassword, rconPort),
		"GameUserSettings.ini": defaultGameUserSettingsINI(),
		"Engine.ini":           defaultEngineINI(),
		"KeyValueStore.ini":    "\n",
		"Bans.json":            "[]\n",
		"Mods.txt":             strings.Join(DefaultModIDs, "\n") + "\n",
		"MapCycle.txt":         "\n",
		"ModScenarios.txt":     "\n",
		"Admins.txt":           "\n",
		"Motd.txt":             "\n",
		"Notes.txt":            "Generated by sandpanel\n",
	}
	for name, body := range defaults {
		path := filepath.Join(root, name)
		if _, err := os.Stat(path); err == nil {
			continue
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
	}
	return nil
}

// GenerateRandomPassword produces a 48-character hex string for use as an RCON password.
func GenerateRandomPassword() string {
	b := make([]byte, 24)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func defaultEngineINI() string {
	return `[SystemSettings]
net.MaxPlayersOverride = 10
`
}

func defaultGameUserSettingsINI() string {
	return `[/Script/ModKit.ModIOClient]

bHasUserAcceptedTerms=True
`
}

func defaultGameINI(rconPassword string, rconPort int) string {
	return fmt.Sprintf(`[Rcon]
bEnabled=true
bAllowConsoleCommands=true
ListenPort=%d
Password=%s

[/Script/Engine.GameNetworkManager]
bMovementTimeDiscrepancyDetection=false
bMovementTimeDiscrepancyResolution=false

[/Script/AIModule.AIPerceptionComponent]
HearingRange=3500
SightRadius=5000
LoseSightRadius=5500
PeripheralVisionAngle=180
`, rconPort, rconPassword)
}

